version: '3'
services:
  web:
    container_name: application
    build: .
    ports:
      - 80:8888
    volumes:
      - .:/usr/src/app/
    links:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: prod
      MYSQL_PASSWORD: prod
      MYSQL_DATABASE: prod
    ports:
      - 3306
    volumes:
      - .:/usr/src/app/